[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pxr-pegtl-dev"
version = "26.8"
description = "Parsing Expression Grammar library used in OpenUSD"
readme = "README.md"
requires-python = ">=3.8"
license-files = ["LICENSE.txt", "NOTICE.txt"]
keywords = ["pixar", "open-usd", "dev"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]

[project.urls]
Repository = "https://github.com/untwine/pxr-pegtl"

[tool.scikit-build]
cmake.version = ">=3.23,<4.3"
cmake.args = [
    "-DCMAKE_INSTALL_INCLUDEDIR=pxr-pegtl/include",
    "-DCMAKE_INSTALL_DATAROOTDIR=pxr-pegtl"
]
sdist.exclude = ["test", ".github"]
