name: pypi-release

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Choose repository to upload to.'
        required: true
        default: testpypi
        type: choice
        options:
          - testpypi
          - pypi

run-name: ${{ inputs.repository }}-release

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: pxr-sdist
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: build_sdist
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: pxr-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: >
            ${{ inputs.repository == 'pypi' &&
            'https://upload.pypi.org/legacy/' ||
            'https://test.pypi.org/legacy/' }}